#language: node_js
#node_js:
#  - "7"

dist: trusty
sudo: required

addons:
  sonarqube:
    organization: "chowanioksource"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
